#!/usr/bin/env python3

# Author: C. J. Burton
# Copyright (C) 2021  C. J. Burton

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# -- HOW TO USE: --
# run ./btc [YOUR_CURRENCY_HERE]
# e.g. ./btc GBP would output:
#  £40556.15

import sys
import json
import urllib.request

# Add your own currency symbol here!
SYMBOLS = {
        "GBP": "£",
        "USD": "$",
        "EUR": "€"
        }

COLOUR = "\033[94m"
NONE = "\033[0m"

def main():
    CURRENCY = sys.argv[1]
    with urllib.request.urlopen("https://blockchain.info/ticker") as url:
        data = json.loads(url.read().decode())
        print(" "+SYMBOLS[CURRENCY]+""+str(data[CURRENCY]['last']))

if __name__ == "__main__":
    main()
