#!/usr/bin/bash
# Get the current song playing through cmus and cmus-remote
# Author: C. Burton

artist=$(cmus-remote -Q | grep ' artist ' | cut -d ' ' -f3-)
song=$(cmus-remote -Q | grep title | cut -d ' ' -f3-)

#echo "Now Playing: $artist - $song"
#echo "🎵: $artist - $song"
echo ": $artist - $song"
